name: CI

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.21.5
        id: go

      - name: Install dependencies
        run: go mod download

      - name: Install linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run linter
        run: golangci-lint run ./...

  merge-to-dev:
    needs: build

    runs-on: ubuntu-latest

    steps:
      # Checkout dev branch
      - uses: actions/checkout@v2
        with:
          ref: dev

      # Merge command
      - name: Merge to dev
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/${{ github.ref }} --no-ff -m "Merge ${{ github.ref }} into dev [skip ci]"

      # Check return value
      - name: Check merge status
        run: |
          MERGE_STATUS=$?
          if [ $MERGE_STATUS -ne 0 ]; then
            echo "Merge failed with status $MERGE_STATUS"
            exit 1
          fi

      # Handle errors
      - name: Handle merge errors
        if: ${{ failure() }}
        run: |
          echo "Merge failed with exit code $?"
          exit 1
