name: CI

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Install dependencies
        run: go mod download

      - name: Run linter
        run: golangci-lint run ./...

      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...

      - name: Convert coverage to LCOV
        run: go tool cover -func=coverage.out -o coverage.info

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.info

  check-coverage:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Check coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: coverage.info
          min_coverage: 30
          exclude: test/*

      - name: Fail if coverage below threshold
        if: ${{ failure() }}
        run: exit 1

  merge-to-dev:
    needs: check-coverage

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
          ref: dev

      - name: Merge to dev
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/${{ github.ref }} --no-ff -m "Merge ${{ github.ref }} into dev [skip ci]"
