name: CI

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Install dependencies
        run: go mod download

      - name: Install linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run linter
        run: golangci-lint run ./...

      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...

      - name: Convert coverage
        run: go tool cover -func=coverage.out -o coverage-info.txt

      - name: Share coverage file
        uses: actions/upload-artifact@v3
        with:
          name: coverage-file
          path: coverage-info.txt

      - name: List files after coverage generation
        run: ls -la

  check-coverage:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Download coverage file
        uses: actions/download-artifact@v3
        with:
          name: coverage-file

      - name: Print directory contents
        run: ls -la

      - name: Print coverage file path
        run: echo "Coverage file path is /home/runner/work/autoprojectsetup/autoprojectsetup/coverage-info.txt"

      - name: Run ChicagoFlutter/lcov-cop
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: coverage-info.txt
          min_coverage: 30
          exclude: test/*

      - name: Fail if coverage below threshold
        if: ${{ failure() }}
        run: exit 1

  merge-to-dev:
    needs: check-coverage

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
          ref: dev

      - name: Merge to dev
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/${{ github.ref }} --no-ff -m "Merge ${{ github.ref }} into dev [skip ci]"
