# .github/workflows/main.yml

name: Main CD

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v -o autoprojectsetup

    - name: Set up gh
      run: |
        curl -sSL https://install.github.com/gh-cli/script.deb.sh | sudo bash
        gh auth login --with-token <<< "${{ secrets.ACTIONS_ACCESS_TOKEN }}"

    - name: Create Release
      run: |
        gh release create ${{ github.sha }} ./autoprojectsetup --title "Release ${{ github.sha }}" --notes "Release of ${{ github.sha }}"