name: CI

on:
  push:
    branches:
      - dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build ./...

    - name: Test
      run: go test ./...

    - name: Lint
      run: golint ./...

  merge-dev:

    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
        ref: main

    - name: Merge dev into main
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge origin/dev --no-ff -m "Merge dev into main [skip ci]"
