# .github/workflows/main.yml

name: Main CD

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build for Linux
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -v -o autoprojectsetup-linux

    - name: Build for MacOS
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -v -o autoprojectsetup-macos

    - name: Build for Windows
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -v -o autoprojectsetup-windows.exe

    - name: Create tag
      run: git tag v${{ github.run_number }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset Linux
      id: upload_release_asset_linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./autoprojectsetup-linux
        asset_name: autoprojectsetup-linux
        asset_content_type: application/octet-stream

    - name: Upload Release Asset MacOS
      id: upload_release_asset_macos
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./autoprojectsetup-macos
        asset_name: autoprojectsetup-macos
        asset_content_type: application/octet-stream

    - name: Upload Release Asset Windows
      id: upload_release_asset_windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./autoprojectsetup-windows.exe
        asset_name: autoprojectsetup-windows.exe
        asset_content_type: application/octet-stream